name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4

      - id: cache
        name: Yarn Cache Dir
        run: echo "value=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Restore Lockfile
        uses: actions/cache@v3
        with:
          path: yarn.lock
          key: yarn-lock-${{ github.sha }}
          restore-keys: yarn-lock-

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.cache.outputs.value }}
          key: yarn-cache-${{ github.sha }}
          restore-keys: yarn-cache-

      - name: Install
        run: yarn


      - name: Build (koishi-plugin-docs)
        run: yarn build


      - name: Release "docs"
        uses: softprops/action-gh-release@v1
        with:
          body: 1
          tag_name: github_run
          name: 1
          files: |
           ./vitepress/dist/*
